#!/bin/bash
#
# Generate TypeScript types from JSON Schemas.
#
# This is the second step in the schema-first workflow:
# 1. Pydantic models -> JSON Schema (via generate_schemas.py)
# 2. JSON Schema -> TypeScript types (this script)
#
# Prerequisites:
#   cd web && npm install
#
# Usage:
#   bash scripts/generate_types.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SCHEMAS_DIR="$PROJECT_ROOT/schemas"
TYPES_DIR="$PROJECT_ROOT/web/types"

# Get schema version from Python
SCHEMA_VERSION=$(python3 -c "import sys; sys.path.insert(0, '$PROJECT_ROOT/src'); from wormgear.io.schema import SCHEMA_VERSION; print(SCHEMA_VERSION)")

echo "Generating TypeScript types from JSON schemas..."

# Check if json-schema-to-typescript is installed (local or global)
if [ -f "$PROJECT_ROOT/web/node_modules/.bin/json2ts" ]; then
    JSON2TS="$PROJECT_ROOT/web/node_modules/.bin/json2ts"
elif command -v json2ts &> /dev/null; then
    JSON2TS="json2ts"
else
    echo "Error: json-schema-to-typescript not found"
    echo "Install with: cd web && npm install"
    exit 1
fi

# Create output directory
mkdir -p "$TYPES_DIR"

# Generate types from main schema
echo "  Processing wormgear-design-v${SCHEMA_VERSION}.json..."
"$JSON2TS" "$SCHEMAS_DIR/wormgear-design-v${SCHEMA_VERSION}.json" \
    --output "$TYPES_DIR/wormgear-design.generated.d.ts" \
    --bannerComment "/* eslint-disable */
/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated from: schemas/wormgear-design-v${SCHEMA_VERSION}.json
 * Generated by: scripts/generate_types.sh
 * Source of truth: src/wormgear/io/loaders.py (Pydantic models)
 *
 * To regenerate:
 *   python scripts/generate_schemas.py
 *   bash scripts/generate_types.sh
 */" \
    --additionalProperties false \
    --strictIndexSignatures

echo "  Generated: $TYPES_DIR/wormgear-design.generated.d.ts"

# Generate enum types
echo "  Processing enums-v${SCHEMA_VERSION}.json..."
"$JSON2TS" "$SCHEMAS_DIR/enums-v${SCHEMA_VERSION}.json" \
    --output "$TYPES_DIR/enums.generated.d.ts" \
    --bannerComment "/* eslint-disable */
/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated from: schemas/enums-v${SCHEMA_VERSION}.json
 * Source of truth: src/wormgear/enums.py
 */" \
    --additionalProperties false

echo "  Generated: $TYPES_DIR/enums.generated.d.ts"

echo ""
echo "TypeScript types generated in: $TYPES_DIR/"
echo ""
echo "To use in JavaScript/TypeScript:"
echo "  import { WormGearDesign, WormParams } from './types/wormgear-design.generated';"
