#!/usr/bin/env python
"""Record golden geometric values for the regression net (Phase 0).

Builds each canonical design defined in ``tests/test_golden_volumes.py`` and
prints the measured volume, bounding-box extents, and face count for both
the worm and the wheel. Output is formatted as a Python literal ready to
paste into the test file.

Use this when:
  - You have legitimately changed geometry generation (rare, requires PR
    review and explicit acknowledgement that the change is intended).
  - You have bumped the ``build123d`` version and need to refresh values
    because the underlying OCC kernel produces slightly different volumes.

Usage:
    uv run --extra dev python scripts/record_golden_volumes.py

The values printed must be reviewed against the previous values: a 0.1 %
volume drift is the noise floor; anything larger should be questioned.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

# Ensure we import from the repo
REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT / "tests"))

from test_golden_volumes import (  # noqa: E402
    GOLDEN_DESIGNS,
    build_pair,
    measure,
)


def main() -> None:
    print("# --- Generated by scripts/record_golden_volumes.py ---")
    print("# Paste the values below into the GOLDEN_VALUES dict in")
    print("# tests/test_golden_volumes.py and review the diff carefully.")
    print()
    print("GOLDEN_VALUES = {")
    for name, spec in GOLDEN_DESIGNS.items():
        print(f"    {name!r}: {{")
        worm, wheel = build_pair(spec)
        worm_meas = measure(worm)
        wheel_meas = measure(wheel)
        print(f"        'worm':  {worm_meas!r},")
        print(f"        'wheel': {wheel_meas!r},")
        print(f"    }},")
    print("}")


if __name__ == "__main__":
    main()
