/* eslint-disable */
/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated from: schemas/wormgear-design-v2.0.json
 * Generated by: scripts/generate_types.sh
 * Source of truth: src/wormgear/io/loaders.py (Pydantic models)
 *
 * To regenerate:
 *   python scripts/generate_schemas.py
 *   bash scripts/generate_types.sh
 */

export type ModuleMm = number;
export type NumStarts = number;
export type PitchDiameterMm = number;
export type TipDiameterMm = number;
export type RootDiameterMm = number;
export type LeadMm = number;
export type AxialPitchMm = number | null;
export type LeadAngleDeg = number;
export type AddendumMm = number;
export type DedendumMm = number;
export type ThreadThicknessMm = number;
/**
 * Thread hand / helix direction
 */
export type Hand = "right" | "left";
export type ProfileShift = number;
/**
 * Worm geometry type
 */
export type WormType = "cylindrical" | "globoid";
export type ThroatReductionMm = number | null;
export type ThroatCurvatureRadiusMm = number | null;
export type LengthMm = number | null;
export type ModuleMm1 = number;
export type NumTeeth = number;
export type PitchDiameterMm1 = number;
export type TipDiameterMm1 = number;
export type RootDiameterMm1 = number;
export type AddendumMm1 = number;
export type DedendumMm1 = number;
export type ProfileShift1 = number;
export type ThroatDiameterMm = number | null;
export type HelixAngleDeg = number | null;
export type WidthMm = number | null;
export type CentreDistanceMm = number;
export type PressureAngleDeg = number;
export type BacklashMm = number;
export type Ratio = number;
export type EfficiencyPercent = number | null;
export type SelfLocking = boolean | null;
/**
 * Bore type: 'none' for solid, 'custom' for specified diameter
 */
export type BoreType = "none" | "custom";
/**
 * Bore diameter in mm. Required when bore_type is 'custom'.
 */
export type BoreDiameterMm = number | null;
export type AntiRotation = string | null;
export type DdcutDepthPercent = number;
export type Size = string;
export type Count = number;
/**
 * Bore type: 'none' for solid, 'custom' for specified diameter
 */
export type BoreType1 = "none" | "custom";
/**
 * Bore diameter in mm. Required when bore_type is 'custom'.
 */
export type BoreDiameterMm1 = number | null;
export type AntiRotation1 = string | null;
export type DdcutDepthPercent1 = number;
export type Type = string;
export type LengthMm1 = number | null;
export type FlangeDiameterMm = number | null;
export type FlangeThicknessMm = number | null;
export type BoltHoles = number | null;
export type BoltDiameterMm = number | null;
/**
 * Worm tooth profile type per DIN 3975
 */
export type WormProfile = "ZA" | "ZK" | "ZI";
export type VirtualHobbing = boolean;
export type HobbingSteps = number;
export type ThroatedWheel = boolean;
export type SectionsPerTurn = number;
export type WormLengthMm = number | null;
export type WheelWidthMm = number | null;

/**
 * Complete worm gear design output from calculator
 */
export interface WormGearDesign {
  worm: WormParams;
  wheel: WheelParams;
  assembly: AssemblyParams;
  features?: Features | null;
  manufacturing?: ManufacturingParams | null;
}
/**
 * Worm dimensional parameters from calculator.
 */
export interface WormParams {
  module_mm: ModuleMm;
  num_starts: NumStarts;
  pitch_diameter_mm: PitchDiameterMm;
  tip_diameter_mm: TipDiameterMm;
  root_diameter_mm: RootDiameterMm;
  lead_mm: LeadMm;
  axial_pitch_mm?: AxialPitchMm;
  lead_angle_deg: LeadAngleDeg;
  addendum_mm: AddendumMm;
  dedendum_mm: DedendumMm;
  thread_thickness_mm: ThreadThicknessMm;
  hand: Hand;
  profile_shift?: ProfileShift;
  type?: WormType | null;
  throat_reduction_mm?: ThroatReductionMm;
  throat_curvature_radius_mm?: ThroatCurvatureRadiusMm;
  length_mm?: LengthMm;
}
/**
 * Wheel dimensional parameters from calculator.
 */
export interface WheelParams {
  module_mm: ModuleMm1;
  num_teeth: NumTeeth;
  pitch_diameter_mm: PitchDiameterMm1;
  tip_diameter_mm: TipDiameterMm1;
  root_diameter_mm: RootDiameterMm1;
  addendum_mm: AddendumMm1;
  dedendum_mm: DedendumMm1;
  profile_shift?: ProfileShift1;
  throat_diameter_mm?: ThroatDiameterMm;
  helix_angle_deg?: HelixAngleDeg;
  width_mm?: WidthMm;
}
/**
 * Assembly parameters from calculator.
 */
export interface AssemblyParams {
  centre_distance_mm: CentreDistanceMm;
  pressure_angle_deg: PressureAngleDeg;
  backlash_mm: BacklashMm;
  hand: Hand;
  ratio: Ratio;
  efficiency_percent?: EfficiencyPercent;
  self_locking?: SelfLocking;
}
/**
 * Manufacturing features for worm and wheel.
 */
export interface Features {
  worm?: WormFeatures | null;
  wheel?: WheelFeatures | null;
}
/**
 * Manufacturing features for worm.
 *
 * bore_type is REQUIRED and must be explicitly specified:
 * - "none": Solid part, no bore (bore_diameter_mm ignored)
 * - "custom": Bore with specified diameter (bore_diameter_mm required)
 */
export interface WormFeatures {
  bore_type: BoreType;
  bore_diameter_mm?: BoreDiameterMm;
  anti_rotation?: AntiRotation;
  ddcut_depth_percent?: DdcutDepthPercent;
  set_screw?: SetScrewSpec | null;
}
/**
 * Set screw specification.
 */
export interface SetScrewSpec {
  size: Size;
  count?: Count;
}
/**
 * Manufacturing features for wheel.
 *
 * bore_type is REQUIRED and must be explicitly specified:
 * - "none": Solid part, no bore (bore_diameter_mm ignored)
 * - "custom": Bore with specified diameter (bore_diameter_mm required)
 */
export interface WheelFeatures {
  bore_type: BoreType1;
  bore_diameter_mm?: BoreDiameterMm1;
  anti_rotation?: AntiRotation1;
  ddcut_depth_percent?: DdcutDepthPercent1;
  set_screw?: SetScrewSpec | null;
  hub?: HubSpec | null;
}
/**
 * Hub specification (wheel only).
 */
export interface HubSpec {
  type?: Type;
  length_mm?: LengthMm1;
  flange_diameter_mm?: FlangeDiameterMm;
  flange_thickness_mm?: FlangeThicknessMm;
  bolt_holes?: BoltHoles;
  bolt_diameter_mm?: BoltDiameterMm;
}
/**
 * Manufacturing/generation parameters.
 *
 * Note: worm_features and wheel_features are NOT stored here.
 * Use WormGearDesign.features instead. Old schemas with features
 * in manufacturing are migrated by upgrade_schema() in schema.py.
 */
export interface ManufacturingParams {
  profile?: WormProfile;
  worm_type?: WormType | null;
  virtual_hobbing?: VirtualHobbing;
  hobbing_steps?: HobbingSteps;
  throated_wheel?: ThroatedWheel;
  sections_per_turn?: SectionsPerTurn;
  worm_length_mm?: WormLengthMm;
  wheel_width_mm?: WheelWidthMm;
}
